### ISSUE TITLE
Ask for tutorial

### ISSUE THREAD

**Issue by wenzl1337** [scipion-em/scipion-em-flexutils#4]
Very nice work ! 
I have installed the plugin in scipion and want to try this program on my dataset. Is there any tutorials or documents for users ?
Thanks !

**Comment by DavidHerreros** [comment]
Hi Wenz,

Thank you so much for your interest in Flexutils plugin! And sorry for the late response.

We are working on a tutorial that will be included in the Scipion documentation web page. Our plan is to release it around mid-June. 

We will keep you updated!

**Comment by DavidHerreros** [comment]
Hi Wenz,

Documentation explaining how to use the Flexutils plugin has been added to the Scipion Wiki! It includes written documentation as well as some complementary video tutorials. [Here](https://scipion-em.github.io/docs/release-3.0.0/docs/user/tutorials/flexibilityHub/main_page.html) you have the link to the main tutorial page.

Hope it is helpful!

**Comment by wenzl1337** [comment]
Thanks ！It helps a lot. I will tell my colleagues and learn the documentation and video together.

Wen

从 Windows 版邮件发送

发件人: DavidHerreros
发送时间: 2023年6月22日 16:10
收件人: scipion-em/scipion-em-flexutils
抄送: wenzl1337; Author
主题: Re: [scipion-em/scipion-em-flexutils] Ask for tutorial (Issue #4)

Hi Wenz,
Documentation explaining how to use the Flexutils plugin has been added to the Scipion Wiki! It includes written documentation as well as some complementary video tutorials. Here you have the link to the main tutorial page.
Hope it is helpful!
